// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oalqgxaufoytgoknociv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hbHFneGF1Zm95dGdva25vY2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDA4OTcsImV4cCI6MjA3MDM3Njg5N30.STkyBkhpztc9-mbgkt6Gi3uwLjZASLsi0etG6zkgz1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});